const ADMIN_STORE_KEY = 'scale-studio-mvp-state-v1';
const ADMIN_SESSION_KEY = 'scale-studio-admin-unlocked-v1';
const ADMIN_PASSWORD = 'ADMIN-DEMO';
const adminApp = document.getElementById('adminApp');
const adminSpaces = [
  { id:'record-wall', name:'唱片墙', store:'上海店', widthMm:1920, heightMm:2880, size:'1920 × 2880 mm', status:'实拍与轮廓已录入', image:'assets/shanghai-record-wall-calibrated.jpg' },
  { id:'peg-wall', name:'洞洞墙', store:'上海店', widthMm:4700, heightMm:2000, size:'4700 × 2000 mm', status:'实拍图待补', image:null },
  { id:'window-wall-mock', name:'临窗展示面', store:'上海店 · Mock', widthMm:3600, heightMm:2400, size:'3600 × 2400 mm', status:'等待真实资料替换', image:null }
];

function adminDefaultState(){return{member:null,access:{activityName:'上海店活动',code:'SHANGHAI-20',maxMembers:20,members:[],startsAt:Date.now(),expiresAt:Date.now()+30*86400000,storeNames:['上海店'],spaceIds:adminSpaces.map(s=>s.id)},projects:[],shares:[]}}
function adminLoad(){try{const parsed=JSON.parse(localStorage.getItem(ADMIN_STORE_KEY));return parsed?{...adminDefaultState(),...parsed,access:{...adminDefaultState().access,...(parsed.access||{})}}:adminDefaultState()}catch{return adminDefaultState()}}
function adminSave(value){localStorage.setItem(ADMIN_STORE_KEY,JSON.stringify(value))}
function adminEscape(value=''){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[c])}
function adminDate(value){return new Date(value).toLocaleDateString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit'})}
function adminToast(message){const n=document.createElement('div');n.className='admin-toast';n.textContent=message;document.getElementById('adminToastRegion').appendChild(n);setTimeout(()=>n.remove(),2400)}
function adminRoute(){return(location.hash.slice(1)||'/overview').split('?')[0]}
function adminNavigate(path){location.hash=path}

function renderAdmin(){if(sessionStorage.getItem(ADMIN_SESSION_KEY)!=='yes'){renderAdminLogin();return}renderAdminShell()}
function renderAdminLogin(){adminApp.innerHTML=`<section class="admin-login"><div class="login-brand"><div class="admin-wordmark"><img src="assets/agi-bar-logo.png" alt="AGI Bar"><span>空间预演管理后台</span></div><div><h1>管理空间、授权与客户项目。</h1><p>这是与用户端完全分离的管理入口。第一版只供店铺管理员使用。</p></div></div><div class="login-form-wrap"><form class="login-form" id="adminLoginForm"><h2>管理员登录</h2><p>输入管理口令进入后台。本地测试版尚未接入正式强认证。</p><label class="field"><span>管理口令</span><input id="adminPassword" type="password" autocomplete="current-password" placeholder="输入管理口令" required></label><button class="admin-button accent" type="submit">进入后台</button></form></div></section>`;document.getElementById('adminLoginForm').onsubmit=e=>{e.preventDefault();if(document.getElementById('adminPassword').value!==ADMIN_PASSWORD){adminToast('管理口令错误。');return}sessionStorage.setItem(ADMIN_SESSION_KEY,'yes');renderAdmin()}}
function renderAdminShell(){const route=adminRoute();adminApp.innerHTML=`<div class="admin-shell"><aside class="admin-sidebar"><div class="admin-wordmark"><img src="assets/agi-bar-logo.png" alt="AGI Bar"><span>空间预演后台</span></div><nav class="admin-nav"><button data-admin-route="/overview">总览</button><button data-admin-route="/projects">客户项目</button><button data-admin-route="/access">活动与授权</button><button data-admin-route="/spaces">空间数据</button></nav><div class="admin-sidebar-footer"><p>当前环境：交互测试</p><a href="index.html#/">打开用户端</a></div></aside><main class="admin-main" id="adminMain"></main></div>`;document.querySelectorAll('[data-admin-route]').forEach(b=>{b.classList.toggle('active',b.dataset.adminRoute===route);b.onclick=()=>adminNavigate(b.dataset.adminRoute)});if(route==='/projects')renderAdminProjects();else if(route==='/access')renderAdminAccess();else if(route==='/spaces')renderAdminSpaces();else renderAdminOverview()}
function adminHeader(label,title,actions=''){return`<header class="admin-topbar"><div><small>${label}</small><h1>${title}</h1></div><div class="admin-actions">${actions}</div></header>`}
function projectRows(projects,state){if(!projects.length)return'<tr><td colspan="6"><div class="empty-admin">还没有客户项目。</div></td></tr>';return projects.map(project=>{const member=state.access.members.find(item=>item.id===project.memberId);return`<tr><td><strong>${adminEscape(project.name)}</strong><br><small>${adminEscape(project.spaceName)}</small></td><td>${adminEscape(member?.nickname||'未知成员')}</td><td>${project.widthMm} × ${project.heightMm} mm</td><td>${adminDate(project.updatedAt)}</td><td><span class="status ${Date.now()>state.access.expiresAt?'expired':''}">${Date.now()>state.access.expiresAt?'只读':'可编辑'}</span></td><td><div class="table-actions"><button class="admin-button ghost small" data-preview="${project.id}">查看内容</button></div></td></tr>`}).join('')}
function renderAdminOverview(){const s=adminLoad(),main=document.getElementById('adminMain');main.innerHTML=adminHeader('运营总览','今天需要关注什么？','<button class="admin-button accent" id="quickNewAccess">管理活动授权</button>')+`<section class="metric-grid"><article class="metric-card"><small>活动成员</small><strong>${s.access.members.length}</strong><span>上限 ${s.access.maxMembers} 人</span></article><article class="metric-card"><small>客户项目</small><strong>${s.projects.length}</strong><span>${s.projects.filter(p=>p.editorPayload).length} 个已开始编辑</span></article><article class="metric-card"><small>空间模板</small><strong>${adminSpaces.length}</strong><span>${adminSpaces.filter(x=>x.status.includes('待')).length} 个待补资料</span></article><article class="metric-card"><small>有效授权</small><strong>${Date.now()<=s.access.expiresAt?1:0}</strong><span>到期 ${adminDate(s.access.expiresAt)}</span></article></section><section class="admin-panel"><div class="panel-head"><div><h2>最近客户项目</h2><p>管理员可以查看客户提交的完整项目内容。</p></div><button class="admin-button ghost small" id="allProjectsBtn">管理全部</button></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>项目</th><th>成员</th><th>尺寸</th><th>更新时间</th><th>状态</th><th>操作</th></tr></thead><tbody>${projectRows([...s.projects].sort((a,b)=>b.updatedAt-a.updatedAt).slice(0,6),s)}</tbody></table></div></section>`;document.getElementById('quickNewAccess').onclick=()=>adminNavigate('/access');document.getElementById('allProjectsBtn').onclick=()=>adminNavigate('/projects');wireAdminPreview()}
function renderAdminProjects(){const s=adminLoad(),main=document.getElementById('adminMain');main.innerHTML=adminHeader('客户内容','客户项目管理','<button class="admin-button accent" id="startProjectBtn">发起客户项目</button>')+`<section class="admin-panel"><div class="panel-head"><div><h2>全部项目</h2><p>按成员、空间和状态检查客户项目。</p></div></div><div class="admin-table-wrap"><table class="admin-table"><thead><tr><th>项目</th><th>成员</th><th>尺寸</th><th>更新时间</th><th>状态</th><th>操作</th></tr></thead><tbody>${projectRows([...s.projects].sort((a,b)=>b.updatedAt-a.updatedAt),s)}</tbody></table></div></section>`;document.getElementById('startProjectBtn').onclick=openAdminProjectForm;wireAdminPreview()}
function openAdminProjectForm(){const s=adminLoad();if(!s.access.members.length){adminToast('请先让客户使用授权码创建成员身份。');return}const layer=document.createElement('div');layer.className='admin-modal-layer';layer.innerHTML=`<section class="admin-modal" role="dialog" aria-modal="true" aria-labelledby="newProjectTitle"><div class="admin-modal-head"><div><small>发起客户项目</small><h2 id="newProjectTitle">指定成员与空间</h2></div><button type="button" data-close-project>×</button></div><form class="admin-modal-body" id="adminProjectForm"><label class="field"><span>项目名称</span><input id="adminProjectName" value="新的活动方案" maxlength="60" required></label><div class="field-grid"><label class="field"><span>项目成员</span><select id="adminProjectMember">${s.access.members.map(m=>`<option value="${m.id}">${adminEscape(m.nickname)}</option>`).join('')}</select></label><label class="field"><span>空间模板</span><select id="adminProjectSpace">${adminSpaces.map(space=>`<option value="${space.id}">${space.store} · ${space.name}</option>`).join('')}</select></label></div><p class="helper">创建后，该项目只会出现在指定成员的“我的项目”中。</p><div class="form-actions"><button class="admin-button accent" type="submit">创建项目</button><button class="admin-button ghost" data-close-project type="button">取消</button></div></form></section>`;document.body.appendChild(layer);layer.querySelectorAll('[data-close-project]').forEach(button=>button.onclick=()=>layer.remove());document.getElementById('adminProjectForm').onsubmit=event=>{event.preventDefault();const space=adminSpaces.find(item=>item.id===document.getElementById('adminProjectSpace').value);s.projects.push({id:`prj_${crypto.randomUUID().replaceAll('-','').slice(0,14)}`,memberId:document.getElementById('adminProjectMember').value,name:document.getElementById('adminProjectName').value.trim(),spaceId:space.id,spaceName:space.name,widthMm:space.widthMm,heightMm:space.heightMm,createdAt:Date.now(),updatedAt:Date.now(),readOnly:false});adminSave(s);layer.remove();renderAdminProjects();adminToast('客户项目已创建。')}}
function adminProjectPreview(project){const space=adminSpaces.find(item=>item.id===project.spaceId);const logos=Array.isArray(project.editorPayload?.logos)?project.editorPayload.logos:[];const background=space?.image?`<img class="admin-preview-bg" src="${space.image}" alt="">`:'<div class="admin-preview-outline"></div>';const overlays=logos.map(item=>`<img class="admin-preview-item" src="${item.src}" alt="" style="left:${Math.max(0,Math.min(100,item.x/project.widthMm*100))}%;top:${Math.max(0,Math.min(100,item.y/project.heightMm*100))}%;width:${Math.max(1,Math.min(100,item.width/project.widthMm*100))}%;transform:rotate(${item.rotation||0}deg)">`).join('');return`<div class="admin-project-preview">${background}${overlays}<span>${logos.length} 个物料</span></div>`}
function openAdminProjectDetail(projectId){const s=adminLoad(),project=s.projects.find(item=>item.id===projectId);if(!project)return;const member=s.access.members.find(item=>item.id===project.memberId);const layer=document.createElement('div');layer.className='admin-modal-layer';layer.innerHTML=`<section class="admin-modal project-detail-modal" role="dialog" aria-modal="true" aria-labelledby="projectDetailTitle"><div class="admin-modal-head"><div><small>${adminEscape(member?.nickname||'未知成员')} · ${adminEscape(project.spaceName)}</small><h2 id="projectDetailTitle">管理客户项目</h2></div><button type="button" data-close-project>×</button></div><form class="admin-modal-body" id="projectDetailForm">${adminProjectPreview(project)}<label class="field"><span>项目名称</span><input id="detailProjectName" value="${adminEscape(project.name)}" maxlength="60" required></label><div class="field-grid"><label class="field"><span>项目状态</span><select id="detailProjectReadOnly"><option value="false" ${project.readOnly?'':'selected'}>允许编辑</option><option value="true" ${project.readOnly?'selected':''}>设为只读</option></select></label><label class="field"><span>项目尺寸</span><input value="${project.widthMm} × ${project.heightMm} mm" disabled></label></div><p class="helper">最近更新：${adminDate(project.updatedAt)}。设置只读后，用户端下一次打开时将看到只读状态。</p><div class="form-actions"><button class="admin-button accent" type="submit">保存项目设置</button><button class="admin-button ghost" data-close-project type="button">关闭</button></div></form></section>`;document.body.appendChild(layer);layer.querySelectorAll('[data-close-project]').forEach(button=>button.onclick=()=>layer.remove());document.getElementById('projectDetailForm').onsubmit=event=>{event.preventDefault();project.name=document.getElementById('detailProjectName').value.trim();project.readOnly=document.getElementById('detailProjectReadOnly').value==='true';project.updatedAt=Date.now();adminSave(s);layer.remove();renderAdminProjects();adminToast('项目设置已保存。')}}
function wireAdminPreview(){document.querySelectorAll('[data-preview]').forEach(button=>button.onclick=()=>openAdminProjectDetail(button.dataset.preview))}
function renderAdminAccess(){const s=adminLoad(),a=s.access,main=document.getElementById('adminMain');main.innerHTML=adminHeader('权限配置','活动与授权')+`<section class="admin-panel form-panel"><div class="panel-head"><div><h2>当前活动</h2><p>保存后用户端账号菜单会同步显示活动名称、时间和授权范围。</p></div></div><form class="panel-body" id="accessForm"><div class="field-grid"><label class="field"><span>活动名称</span><input id="activityName" value="${adminEscape(a.activityName)}" required></label><label class="field"><span>共享授权码</span><input id="accessCode" value="${adminEscape(a.code)}" required></label><label class="field"><span>开始日期</span><input id="startsAt" type="date" value="${new Date(a.startsAt).toISOString().slice(0,10)}" required></label><label class="field"><span>到期日期</span><input id="expiresAt" type="date" value="${new Date(a.expiresAt).toISOString().slice(0,10)}" required></label><label class="field"><span>成员上限</span><input id="maxMembers" type="number" min="1" max="20" value="${a.maxMembers}" required></label><label class="field"><span>授权店铺</span><select id="storeScope"><option>上海店</option></select></label></div><p class="helper">共享授权人数上限不能超过 20。正式后端会使用数据库事务执行全局人数限制。</p><div class="form-actions"><button class="admin-button accent" type="submit">保存授权配置</button><button class="admin-button ghost" id="copyInviteBtn" type="button">复制邀请入口</button></div></form></section>`;document.getElementById('accessForm').onsubmit=e=>{e.preventDefault();a.activityName=document.getElementById('activityName').value.trim();a.code=document.getElementById('accessCode').value.trim().toUpperCase();a.startsAt=new Date(`${document.getElementById('startsAt').value}T00:00:00`).getTime();a.expiresAt=new Date(`${document.getElementById('expiresAt').value}T23:59:59`).getTime();a.maxMembers=Math.min(20,Math.max(1,Number(document.getElementById('maxMembers').value)));s.access=a;adminSave(s);adminToast('活动授权已保存。')};document.getElementById('copyInviteBtn').onclick=async()=>{const link=`${location.origin}${location.pathname.replace(/admin\.html$/,'')}index.html#/access`;try{await navigator.clipboard.writeText(link);adminToast('邀请入口已复制。')}catch{window.prompt('复制邀请入口',link)}}}
function renderAdminSpaces(){const main=document.getElementById('adminMain');main.innerHTML=adminHeader('模板资料','空间数据','<button class="admin-button accent" id="addSpaceBtn">新增空间</button>')+`<section class="space-admin-grid">${adminSpaces.map(space=>`<article class="space-admin-card"><small>${space.store}</small><h3>${space.name}</h3><code>${space.size}</code><p>${space.status}</p><button class="admin-button ghost small" data-space-edit="${space.id}">管理资料</button></article>`).join('')}</section>`;document.getElementById('addSpaceBtn').onclick=()=>adminToast('新增空间表单将在接入云端数据后启用。');document.querySelectorAll('[data-space-edit]').forEach(b=>b.onclick=()=>adminToast('当前可继续补充该空间的实拍图与校准数据。'))}
window.addEventListener('hashchange',renderAdmin);renderAdmin();
